# Generated by Django 5.0.1 on 2025-11-03 09:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fine', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6, verbose_name='每日罚金')),
                ('max_renewals', models.PositiveIntegerField(default=1, verbose_name='最大续借次数')),
                ('loan_period_days', models.PositiveIntegerField(default=30, verbose_name='借阅天数')),
            ],
            options={
                'verbose_name': '罚款规则',
                'verbose_name_plural': '罚款规则',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('due_at', models.DateTimeField(verbose_name='应还时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('status', models.CharField(choices=[('borrowed', '借出'), ('returned', '已归还'), ('overdue', '逾期')], db_index=True, default='borrowed', max_length=16, verbose_name='状态')),
                ('renew_count', models.PositiveIntegerField(default=0, verbose_name='续借次数')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='罚款金额')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='library.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'indexes': [models.Index(fields=['status'], name='borrowing_b_status_4f1f75_idx'), models.Index(fields=['borrowed_at'], name='borrowing_b_borrowe_5d4793_idx')],
            },
        ),
    ]
